### ISSUE TITLE
Vector dot product accelerator

### ISSUE THREAD

**Issue by MohanaMadhumita** [HPC-Lab-IITB/Melodica#2]
- [ review mohil's code ]

- [ define input output types ]

**Comment by nirajnsharma** [comment]
@MohanaMadhumita Please create a new repository called TCA (for tightly coupled accelerators). Let's do our accelerator experimentation on that repository and reflect learnings here.

**Comment by MohanaMadhumita** [comment]
Hey Niraj!
I've seen you have created one repository.
I'll keep using that!


-Madhumita
